server.port: 8080

spring: 
datasource:
url: jdbc:postgersql://localhost:5432/academia?useTimezone-true&serverTimezone=UTC&useLegacyDate
username: lukas 
password: root

jpa:  
show-sql: true
hibernate: 
  ddl-auto: auto
  properties: 
  hibernate.format_sql: true

  logging: 
  level:
  org:
  hibernate:
  type: trace
